name = "BiPCHIP"
uuid = "8458cfa5-3121-4924-9858-a90f7c271906"
authors = ["Stepan Oslejsek"]
version = "1.0.0-DEV"

[deps]
BSplineKit = "093aae92-e908-43d7-9660-e50ee39d5a0a"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"

[compat]
BSplineKit = "0.19.1"
HiGHS = "1.20.0"
JuMP = "1.29.2"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
